### ISSUE TITLE
Render Table of Contents

### ISSUE THREAD

**Issue by BryanHo10** [WycliffeAssociates/quick_usfm_converter#11]
## User Story
As a User, I want to have a table of contents page template added to the front of the document before the HTML content rendered from the USFM file so that I will be able to locate particular sections and identify which sections are included.  

## Acceptance Criteria
```
\h Matthew
\toc1 The Gospel According to Matthew
\toc2 Matthew
\toc3 Mat
```

![image](https://user-images.githubusercontent.com/23038573/58974770-43dbd980-8791-11e9-9164-d7efe01a788f.png)

**Comment by BryanHo10** [comment]
Reuben
- Make hyperlinks
- Option of table of contents
- Have something at the top (navigation)

**Comment by BryanHo10** [comment]
Want both to provide the preferred formatting of Table of Contents

**Comment by ChrisJarka** [comment]
I was able to add a TOC to the document and the HTML file that I created.

The choice to have a TOC was not held persistent from the DOC choice to the HTML choice.
