### ISSUE TITLE
Provide option to Justify text in columns

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/quick_usfm_converter#12]
## User Story
As a User, I want the text sent to the layout to be justified in the column(s) so that it is easier to read

## Acceptance Criteria
? Only Justified Text
? What if not chosen, default to left / right depending on reading direction

![image](https://user-images.githubusercontent.com/23038573/59062396-b1603680-8873-11e9-99ef-d92cdebfbfec.png)

**Comment by BryanHo10** [comment]
? R2L or L2R justification

**Comment by BryanHo10** [comment]
default depending on reading direction
