### ISSUE TITLE
Choose between 8 1/2 x 11 and A4 formats

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/quick_usfm_converter#13]
## User Story
As a User I would like to specify the paper size of the layout so that I can printout to A4 and 8 1/2 x 11 size paper.

## Acceptance Criteria

**Comment by BryanHo10** [comment]
Non Issue until exported to Docx or Odt. System print dialog.

Until export Docx - > specify which size of paper

**Comment by BryanHo10** [comment]
Ask to show what the problem is

**Comment by BryanHo10** [comment]
page breaks after every chapter

**Comment by BryanHo10** [comment]
## User Story
As a User I would like the option to add page breaks after every chapter, so that I can distribute chapter pages to people for translation.

## Acceptance Criteria
