### ISSUE TITLE
Include timestamp of HTML conversion into the document footer

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/quick_usfm_converter#15]
## User Story
As a User I would like the Date and Time of the file conversion from USFM to HTML to be included in the footer of each page of the generated document.

## Acceptance Criteria
? System Date and Time
? Formatting

**Comment by BryanHo10** [comment]
HTML -- For now, just bottom of the page
Until Docx/ODT renderer -> Page Footer

**Comment by BryanHo10** [comment]
International formatting(preferred)/ write  out month

**Comment by BryanHo10** [comment]
Footer - Bottom of every page
Time - exclude seconds (H:M)
