### ISSUE TITLE
Include the CC by SA info into the footer of the generated document

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/quick_usfm_converter#16]
## User Story
As a User I need the CC by SA information to be included at the bottom of each page to be in compliance with the usage of copyright.

## Acceptance Criteria
Check with Craig for what this should be.

**Comment by BryanHo10** [comment]
- HTML Render  (Non-Organizational bias)
- Should be used freely by anyone

- Possibly, extend api on top of current api  (overloading is fine, no breaking changes)
Build unit tests from current api, and test against new api

**Comment by BryanHo10** [comment]
Time-stamp on left
Page number in center
CC by SA on right (no version)
