### ISSUE TITLE
drag and drop

### ISSUE THREAD

**Issue by ccdicamillo** [WycliffeAssociates/quick_usfm_converter#54]
When I open the drag and drop screen, it does not allow me to drag/drop any USFM files. The only way to access files was to hit Enter and use the Browse Folders popup.

**Comment by ChrisJarka** [comment]
I like the fact that I can drag and drop into either the gray area at the top right as well as into the list area below.

**Comment by ChrisJarka** [comment]
When I click on the Browse Folder button  - I do not see any files in the folder I choose. I can only add folders (only the UFM files get imported) See picture.

Perhaps changing the button to "Browse **for** Folder" ? 

Perhaps changing the instructions to:
You can select a folder or files from your computer then drag and drop them into this area to import. 

![Snag_b811e60](https://user-images.githubusercontent.com/9850185/124965990-b82c7b00-dff0-11eb-808e-57f92878a6b4.png)
